/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VistaController;

import javax.swing.table.DefaultTableModel;
import Controller.UsuarioController;
import Model.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author nicolas
 */
public class VistaCrearUsuario extends javax.swing.JInternalFrame {

    DefaultTableModel model = new DefaultTableModel();
    
    public VistaCrearUsuario() {
        initComponents();
        
        model.addColumn("USUARIO");
        model.addColumn("NOMBRE");
        model.addColumn("APELLIDO");
        model.addColumn("RUT");
     
        
        llenarTablaUsuarios();
        
     
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nombreUsuario = new javax.swing.JTextField();
        txt_usuario = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_rut = new javax.swing.JTextField();
        btn_Editar = new javax.swing.JButton();
        btn_Agregar = new javax.swing.JButton();
        txt_contraseña = new javax.swing.JPasswordField();
        checkBox_Admin = new javax.swing.JCheckBox();
        chekBox_estado = new javax.swing.JCheckBox();

        setClosable(true);

        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaUsuarios);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel1.setText("EDICION DE USUARIO");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel3.setText("Apellido:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel4.setText("Rut:");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel5.setText("User:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel6.setText("Contraseña:");

        btn_Editar.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        btn_Editar.setText("Editar");
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });

        btn_Agregar.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        btn_Agregar.setText("Agregar");
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });

        checkBox_Admin.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        checkBox_Admin.setText("Administrador del Sistema");

        chekBox_estado.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        chekBox_estado.setText("Activar Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBox_Admin)
                        .addGap(37, 37, 37)
                        .addComponent(chekBox_estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_rut, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(txt_apellido)
                            .addComponent(txt_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(txt_nombreUsuario)))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkBox_Admin)
                            .addComponent(chekBox_estado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Agregar)
                            .addComponent(btn_Editar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        String usuario = txt_usuario.getText().trim();
        String nombre = txt_nombreUsuario.getText().trim();
        String apellido = txt_apellido.getText().trim();
        String rut = txt_rut.getText().trim();
        String contraseña = txt_contraseña.getText().trim();
        int tipo = 0;
        int activo = 0;
        
        boolean estado = chekBox_estado.isSelected();
        boolean admin = checkBox_Admin.isSelected();
        
        if (admin) {
            tipo = 1;
            
        } else {
            tipo = 0;
        }
        
        if (estado) {
            activo = 1;
            
        } else {
            activo = 0;
        }
        
        if (!usuario.isEmpty()&&!nombre.isEmpty()&&!apellido.isEmpty()&&!rut.isEmpty()&&!contraseña.isEmpty()){
                  
          
            
            
            try {
    
    boolean sucess = Usuario.verificacionDuplicado(usuario, rut);
                if (!sucess) {
                    
                        boolean evento = Usuario.insertarUsuario(nombre, apellido, rut, contraseña, usuario, activo, tipo);              if (evento) {
                JOptionPane.showMessageDialog(this, "Usuario agregado exitosamente");
            } else {
                   JOptionPane.showMessageDialog(this, "No se pudo agregar usuario");
            }
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Ya existe un usuario con ese Nombre/Rut");
                }
              

        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, "Problema con conexion en base de datos o insercion de datos en la tabla vistausariocontrolleragerar.usuario");
        } 
          
            
  
                   
        }
else{
            JOptionPane.showMessageDialog(this, "Debe completar todos los datos del ususario");
                           }
        
        
        
          
                
        
limpiar();
        
    }//GEN-LAST:event_btn_AgregarActionPerformed

    
    
    
    
    
    
    
    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed


        
        
        
        
        
        
        
    }//GEN-LAST:event_btn_EditarActionPerformed

    /**/

    
    

    
    

    

           
          
         

        
       
   public void llenarTablaUsuarios(){
   model.setRowCount(0);
   TablaUsuarios.setModel(model);
   
       try {
           
           ArrayList<Usuario> listaUsuarios = Usuario.todosUsuarios();
           
           for (Usuario UsuarioIndex : listaUsuarios) {
               Object [] objeto = new Object[4];
                       objeto[0]= UsuarioIndex.getUsuario();
                       objeto[1]= UsuarioIndex.getUsuarioNombre();
                       objeto[2]= UsuarioIndex.getUsuarioApellido();
                       objeto[3]= UsuarioIndex.getUsuarioRut();
                              
                       
                       model.addRow(objeto);
               
           }
           
       } catch (Exception e) {
       }
   
   
   
   
   
   }  
    
    

    
    public void limpiar(){
    
        txt_usuario.setText("");
        txt_nombreUsuario.setText("");
        txt_apellido.setText("");
        txt_rut.setText("");
        txt_contraseña.setText("");
        checkBox_Admin.setSelected(false);
        chekBox_estado.setSelected(false);
        llenarTablaUsuarios();
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JCheckBox checkBox_Admin;
    private javax.swing.JCheckBox chekBox_estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JTextField txt_nombreUsuario;
    private javax.swing.JTextField txt_rut;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
