/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VistaController;

import javax.swing.table.DefaultTableModel;
import Controller.UsuarioController;
import Model.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author nicolas
 */
public class VistaCrearUsuario extends javax.swing.JInternalFrame {

    DefaultTableModel model = new DefaultTableModel();
    
    public VistaCrearUsuario() {
        initComponents();
        
        model.addColumn("NOMBRE");
        model.addColumn("APELLIDO");
        model.addColumn("RUT");
        model.addColumn("USER NAME");
        model.addColumn("ID");
        refrescarTabla();
        llenarCombos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nombreUsuario = new javax.swing.JTextField();
        txt_usuario = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_rut = new javax.swing.JTextField();
        btn_Editar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btn_Agregar = new javax.swing.JButton();
        txt_contraseña = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        combo_estado = new javax.swing.JComboBox<>();

        setClosable(true);

        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaUsuarios);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel1.setText("EDICION DE USARIO");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel3.setText("Apellido:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel4.setText("Rut:");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel5.setText("User:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel6.setText("Contraseña:");

        btn_Editar.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        btn_Editar.setText("Editar");
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });

        btn_Agregar.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        btn_Agregar.setText("Agregar");
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel8.setText("Estado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_rut, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                            .addComponent(txt_apellido)
                                            .addComponent(txt_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                            .addComponent(txt_nombreUsuario)))
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(combo_estado, 0, 280, Short.MAX_VALUE)
                                            .addComponent(txt_contraseña))))
                                .addGap(0, 43, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(combo_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(btn_Agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Editar)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        String nombre = txt_nombreUsuario.getText().trim();
        String apellido = txt_apellido.getText().trim();
        String rut = txt_rut.getText().trim();
        String contraseña = txt_contraseña.getText().trim();
        String usuario = txt_usuario.getText().trim();
        
        int estado = 0;
        String estadoString = combo_estado.getSelectedItem().toString();
        
        
        
        if (estadoString.contains("activado")) {
            estado = 1;
            
        }
        
                if (estadoString.contains("desactivado")) {
            estado = 2;
            
        }
                
                
        
        UsuarioController usuarioController = new UsuarioController();
        
        boolean evento = usuarioController.InsertarNuevoUsuario(nombre, apellido, usuario, contraseña, rut, estado);
        
        if (evento) {
            
            JOptionPane.showMessageDialog(this, "USUARIO CREADO CORRECTAMENTE");
            
        }
        
     refrescarTabla();
     limpiar();
        
    }//GEN-LAST:event_btn_AgregarActionPerformed

    
    
    
    
    
    
    
    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed

        String nombre = txt_nombreUsuario.getText().trim();
        String apellido = txt_apellido.getText().trim();
        String rut = txt_rut.getText().trim();
        String contraseña = txt_contraseña.getText().trim();
        String usuario = txt_usuario.getText().trim();
        
        
         int estado = 0;
        String estadoString = combo_estado.getSelectedItem().toString();
        
        
        
        if (estadoString.contains("activado")) {
            estado = 1;
            
        }
        
                if (estadoString.contains("desactivado")) {
            estado = 2;
            
        }
        
        UsuarioController usuarioController = new UsuarioController();
        
        boolean evento = usuarioController.editarUsuario(nombre, apellido, usuario, contraseña, rut, estado);
        
        if (evento) {
            
            JOptionPane.showMessageDialog(this, "USUARIO MODIFICADO CORRECTAMENTE");
            
        }
        
     refrescarTabla();
     limpiar();
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btn_EditarActionPerformed

    /**/

    
    

    
    
    
     //user_id , usuarioNombre, usuarioApellido, usuarioRut
    
    public void refrescarTabla(){
        model.setRowCount(0);
        TablaUsuarios.setModel(model);
        
        UsuarioController usuarioController = new UsuarioController();
        ArrayList <Usuario> todosLosUsuarios = usuarioController.ListarTodoUsuario();
        
       
        
        
        for (Usuario usuarioIndex : todosLosUsuarios) {
            
            Object index [] = new Object [6];
            index[0] = usuarioIndex.getUsuarioNombre();
            index[1] = usuarioIndex.getUsuarioApellido();
            index[2] = usuarioIndex.getUsuarioRut();
            index[3] = usuarioIndex.getUsuario();
            index[4] = usuarioIndex.getUser_id();
            index[5] = usuarioIndex.getVisible();
            
            
            
            if ((int) index[5] == 1) {
                model.addRow(index);
            }
            
            
           
            
        }
         

        
       
        
    }
    
    
    public void llenarCombos(){
    
        ArrayList<String> estadosStrings = new ArrayList<>();
        estadosStrings.add("activado");
        estadosStrings.add("desactivado");
        
        
        for (String estados : estadosStrings) {
            combo_estado.addItem(estados);
        }
        
    }
    
    /*
    public void llenarComboUsuarios(){
    
        UsuarioController usuarioController = new UsuarioController();
        ArrayList <Usuario> todosLosUsuarios = usuarioController.ListarTodoUsuario();
        
        for (Usuario usuario : todosLosUsuarios) {
            combo_usuarios.addItem(usuario.getUsuario());
            
        }
        
        ArrayList<String> estadosStrings = new ArrayList<>();
        estadosStrings.add("activado");
        estadosStrings.add("desactivado");
        
        
        for (String estados : estadosStrings) {
            combo_estado.addItem(estados);
        }
        
    }
    */
    
    
    public void limpiar(){
    
        txt_usuario.setText("");
        txt_nombreUsuario.setText("");
        txt_apellido.setText("");
        txt_rut.setText("");
        txt_contraseña.setText("");
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JComboBox<String> combo_estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JTextField txt_nombreUsuario;
    private javax.swing.JTextField txt_rut;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
